### PR TITLE
Update Axios to 1.4.0

### PR DESCRIPTION
**Pull request by jstasiak**
We've been using an old version that doesn't have a feature that I want to use (isAxiosError) so I figured let's update to the latest one.

### CODE REVIEW

**Comment by stoich** [comment]
quite the jump. def safe right?

**Review by stoich — APPROVED** [review]

**Comment by jstasiak** [comment]
Yeah it's quite big but I made some requests using this version and everything worked.

**Comment by jstasiak** [comment]
Actually there's one thing that I forgot to test (request interceptors working), I'll do that now

**Comment by jstasiak** [comment]
Actually not an issue – we don't use interceptors for requests, just responses.

**Pull request merged**
