### PR TITLE
Bump version (major)

### PR DESCRIPTION
**Pull request by rbruggem**
Action to bump version (major) was triggered. Check changes and approve accordingly.

### CODE REVIEW

**Comment by rbruggem** [comment]
Major version feels too much.
Close?

**Comment by rbruggem** [comment]
@raguiar9080 @festinaj ?

**Comment by raguiar9080** [comment]
I'm under the impression @jstasiak opened this hence by reluctant to close without feedback, but I wonder now if it was by mistake since there's been no interaction here.

**Comment by jstasiak** [comment]
I had nothing to do with this PR (I think)

**Comment by raguiar9080** [comment]
Ok, just wanted to make sure. I'll close it 👍

**Pull request closed without merging**
