### PR TITLE
Upgrade openapi-typescript-codegen to v0.1.16

### PR DESCRIPTION
**Pull request by rbruggem**
This change includes a fix to non-JSON responses.
Non-JSON response are now not modified.

### CODE REVIEW

**Review by jstasiak — APPROVED** [review]
Do we need to regenerate the code as part of this PR?

**Comment by rbruggem** [comment]
> Do we need to regenerate the code as part of this PR?

Is it not automatic?

**Comment by jstasiak** [comment]
Good question, I don't actually remember I think.

**Comment by raguiar9080** [comment]
I do think it should be automatic but honestly would have to check 😅

**Pull request closed without merging**
