### PR TITLE
Client auto update

### PR DESCRIPTION
**Pull request by rbruggem**
Underlying schema has changed. Check changes and approve accordingly. This will not create any release, simply assimilate changes on the schema.

### CODE REVIEW

**Comment by jstasiak** [comment]
@raguiar9080 we may have a bug, there's this empty string enum member defined https://github.com/lune-climate/lune-docs/blob/0f4841b919424bdd23b2e6b38d686bfafc8670f9/docs/src/.vuepress/public/openapi.yml#L2894= but it's missing from this PR

**Comment by jstasiak** [comment]
I'll have a look at that, I think it'll require some special treatment

**Comment by raguiar9080** [comment]
> I'll have a look at that, I think it'll require some special treatment

Let me know if you need help. I'm assuming he's ignoring the empty string since he probably can't convert it to a valid enum value 🤔

**Comment by rbruggem** [comment]
What's happening here?

**Comment by raguiar9080** [comment]
> What's happening here?

The base client generator does not deal with empty strings in an enum. We've added them as a repo enum, so we need to handle them.

**Pull request merged**
